### ISSUE TITLE
didcomm support

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/did-sdk#16]
initial support for https://identity.foundation/didcomm-messaging/spec/
should be broken into a set of issues to handle
- message types
- signing / verifying
- message encryption
- different protocols supported
- threading
- using different key types
- QR code generation?

**Comment by georgejpadayatti** [comment]
@decentralgabe Different protocols ? Hyperledger aries, DIF protocols e.t.c ?

**Comment by decentralgabe** [comment]
@georgejpadayatti the latest DIDComm work is taking place in DIF. The TBD team is a member and is following the group's progress. https://identity.foundation/working-groups/did-comm.html

**Comment by georgejpadayatti** [comment]
In my opinion, did-sdk should have support for both DIF and Hyperledger aries. Both communities have an existing and eager audience who could benefit from a unified sdk.

**Comment by decentralgabe** [comment]
@georgejpadayatti it was my impression that the work began in Hyperledger Aries and has since moved over to DIF. I believe that's where all the new work continues. Is that no longer true?

**Comment by georgejpadayatti** [comment]
It's a bit confusing to be honest. Since I am part of both these communities, personally I feel DIF is where active work is going on, but due to this spec evolves rapidly. Aries community is bit stagnant, but is suitable for implementers because of that. For e.g. IDUnion from Germany has adopted AIP 1.0 for their wallets, Findy from Finland seems to follow them.

**Comment by decentralgabe** [comment]
closed in support of https://github.com/TBD54566975/did-sdk/issues/62
